# Generated by Django 6.0.6 on 2026-06-12 06:14

from django.db import migrations


def add_coupon_permission(apps, schema_editor):
    """
    Crea el permiso 'marketing.gestionar_cupones' (spec Carrito y Pedidos)
    y lo asocia al perfil 'Administrador del Sistema' con alcance 'todos' si existe.
    """
    PermissionAtom = apps.get_model('users', 'PermissionAtom')
    Profile = apps.get_model('users', 'Profile')
    ProfilePermission = apps.get_model('users', 'ProfilePermission')

    atom, _ = PermissionAtom.objects.get_or_create(
        code='marketing.gestionar_cupones',
        defaults={
            'module': 'marketing',
            'description': 'Crear y administrar cupones de descuento',
        }
    )

    admin_profile = Profile.objects.filter(name='Administrador del Sistema').first()
    if admin_profile:
        ProfilePermission.objects.get_or_create(
            profile=admin_profile,
            permission=atom,
            defaults={'scope': 'todos'}
        )


def remove_coupon_permission(apps, schema_editor):
    PermissionAtom = apps.get_model('users', 'PermissionAtom')
    PermissionAtom.objects.filter(code='marketing.gestionar_cupones').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_coupon_permission, remove_coupon_permission),
    ]
