# Generated by Django 6.0.6 on 2026-06-12 06:29

from django.db import migrations


def ensure_client_cart_permissions(apps, schema_editor):
    """
    Precondición de la spec 'Carrito y Pedidos': el perfil base
    "Comprar en la tienda" debe incluir 'carrito.gestionar' y 'carrito.checkout'.
    Algunas bases restauradas desde backups antiguos no tienen 'carrito.checkout'.
    """
    PermissionAtom = apps.get_model('users', 'PermissionAtom')
    Profile = apps.get_model('users', 'Profile')
    ProfilePermission = apps.get_model('users', 'ProfilePermission')

    client_profile = Profile.objects.filter(name='Comprar en la tienda').first()
    if not client_profile:
        return

    required = [
        ('carrito.gestionar', 'cart', 'Agregar, editar y eliminar del carrito'),
        ('carrito.checkout', 'cart', 'Confirmar pedidos'),
    ]
    for code, module, desc in required:
        atom, _ = PermissionAtom.objects.get_or_create(
            code=code,
            defaults={'module': module, 'description': desc}
        )
        ProfilePermission.objects.get_or_create(
            profile=client_profile,
            permission=atom,
            defaults={'scope': 'propios'}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_coupon_permission'),
    ]

    operations = [
        migrations.RunPython(ensure_client_cart_permissions, migrations.RunPython.noop),
    ]
