# Generated by Django 5.0.6 on 2026-06-13 17:34

from django.db import migrations, models

# Únicos permisos donde el alcance Propios/Todos cambia el comportamiento.
SCOPE_AWARE = [
    'catalogo.editar_producto',
    'catalogo.eliminar_producto',
    'catalogo.gestionar_stock',
    'pedidosventas.ver',
    'pedidosventas.cambiar_estado',
]


def set_scope_aplica(apps, schema_editor):
    PermissionAtom = apps.get_model('users', 'PermissionAtom')
    ProfilePermission = apps.get_model('users', 'ProfilePermission')

    # Los permisos no incluidos en SCOPE_AWARE no usan el alcance -> scope_aplica=False
    PermissionAtom.objects.exclude(code__in=SCOPE_AWARE).update(scope_aplica=False)
    PermissionAtom.objects.filter(code__in=SCOPE_AWARE).update(scope_aplica=True)

    # Normalizar asignaciones existentes: donde el alcance no aplica, forzar 'todos'
    # (corrige los grants "muertos" con 'propios', ej. cupones/auditoría/perfiles).
    ProfilePermission.objects.filter(permission__scope_aplica=False).update(scope='todos')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_order_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionatom',
            name='scope_aplica',
            field=models.BooleanField(default=True, help_text="Si es False, el alcance (Propios/Todos) no tiene sentido para este permiso (recurso per-usuario o función global) y se fija en 'todos'. El panel oculta el selector."),
        ),
        migrations.RunPython(set_scope_aplica, noop),
    ]
