# Generated by Django 5.0.6 on 2026-06-13 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Dueño de la sesión; cada usuario solo ve sus propios chats', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
