# Generated by Django 5.0.6 on 2026-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_banner_product_min_stock_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slot',
            field=models.CharField(choices=[('hero', 'Hero (imagen grande arriba del catálogo)'), ('carousel', 'Carrusel (franja debajo del hero)')], default='carousel', help_text='Ubicación del catálogo público donde se muestra', max_length=20),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición dentro del slot'),
        ),
    ]
