# Generated by Django 5.0.6 on 2026-06-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_banner_slot_alter_banner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtítulo (solo aplica al Hero)', max_length=300),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text='Título principal (en Hero, el encabezado grande)', max_length=150),
        ),
    ]
