# Generated by Django 5.0.6 on 2026-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_banner_subtitle_alter_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='overlay_opacity',
            field=models.PositiveIntegerField(default=55, help_text='Opacidad del oscurecido sobre la imagen (0-100), para legibilidad del texto en el Hero'),
        ),
    ]
