# Generated by Django 5.0.6 on 2026-06-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_banner_overlay_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Marca o fabricante', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alto en centímetros', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largo en centímetros', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('cemento', 'Cemento / Hormigón'), ('madera', 'Madera'), ('metal', 'Metal / Acero'), ('plastico', 'Plástico / PVC'), ('ceramico', 'Cerámico'), ('vidrio', 'Vidrio'), ('pintura', 'Pintura / Química'), ('electrico', 'Eléctrico'), ('otro', 'Otro')], help_text='Material principal del producto', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_sale',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('m', 'Metro'), ('m2', 'Metro cuadrado'), ('m3', 'Metro cúbico'), ('litro', 'Litro'), ('bolsa', 'Bolsa'), ('rollo', 'Rollo'), ('par', 'Par'), ('caja', 'Caja'), ('pallet', 'Pallet')], default='unidad', help_text='Unidad en la que se vende el producto', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho en centímetros', max_digits=8, null=True),
        ),
    ]
