# Generated by Django 5.0.6 on 2026-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_brand_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding_error',
            field=models.CharField(blank=True, help_text='Último error al generar el embedding (vacío si no hubo)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se generó exitosamente el embedding', null=True),
        ),
    ]
