# Generated by Django 5.0.6 on 2026-06-13 06:26

from django.db import migrations, models


def paid_to_preparing(apps, schema_editor):
    """Convierte los pedidos en el estado obsoleto 'paid' al nuevo 'preparing'."""
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='paid').update(status='preparing')


def preparing_to_paid(apps, schema_editor):
    """Reversa: 'preparing' vuelve a 'paid'."""
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='preparing').update(status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_amount_coupon_cart_order_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'En preparación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.RunPython(paid_to_preparing, preparing_to_paid),
    ]
