# Generated by Django 5.0.6 on 2026-06-14 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        ('users', '0007_activesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Si fue cancelada y no debe renovar al vencer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('trialing', 'En prueba'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Duración del período en días')),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Días de prueba gratis al inicio (0 = sin prueba)')),
                ('auto_renew', models.BooleanField(default=True, help_text='Si renueva automáticamente al vencer (cobro simulado)')),
                ('is_active', models.BooleanField(default=True, help_text='Si el plan se ofrece a los clientes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profiles', models.ManyToManyField(blank=True, help_text='Perfiles que se asignan al usuario mientras el plan esté activo', related_name='plans', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid_simulated', 'Pagado (simulado)')], default='paid_simulated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.plan')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_plan',
            field=models.ForeignKey(blank=True, help_text='Plan configurable vigente (nuevo sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='orders.plan'),
        ),
    ]
