# Generated by Django 5.0.6 on 2026-06-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_mp_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_payment_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
